- ## **Introduction
	- Ethan Page
	- Introductory Pentesting
- **Notetaking**
	- Effective notetaking is very important
	- Joplin on Kali
- **Scope**
	- Spreadsheet or something to keep up with what you've covered and what we still have left
